# Overview

The main aim of this project is to perform some data cleaning in the [JBeans Raw Dataset](https://drive.google.com/drive/folders/1giaGOhJYWIXfZzy-zxmbrUIOB9Y_ROdu) and get it ready for cleaning 

The main aim of this project is to practice some of the skills I have learnt in data cleaning and data analysis. 


#### Requirements

The directory of this notebook contains a CSV file which contains all the raw data in the Jeans Raw Dataset. If the CSV file is missing you can download it [here](https://drive.google.com/drive/folders/1giaGOhJYWIXfZzy-zxmbrUIOB9Y_ROdu).

The following assumptions have been made:
- The CSV file is in the current directory
- The CSV file is named raw_survey_data.csv

In [1]:
# if raw_survey_data.csv is in the current directory it would be outputed when you run 
# this cell 

!ls | grep raw_survey_data.csv$

raw_survey_data.csv

In [364]:
# importing packages with their natural alias

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [3]:

# Here we store all the constants we need in this project
CSV_FILENAME = 'raw_survey_data.csv'

In [5]:
# Loading the CSV to a dataframe
raw_data = pd.read_csv(CSV_FILENAME, dtype=np.object)

In [6]:
# Performing basic checks on the data 
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19835 entries, 0 to 19834
Columns: 284 entries, Unnamed: 0 to What country do you live in?
dtypes: object(284)
memory usage: 43.0+ MB

In [7]:
raw_data.columns

Index(['Unnamed: 0',
       'Is Python the main language you use for your current projects?',
       'None:What other language(s) do you use?',
       'Java:What other language(s) do you use?',
       'JavaScript:What other language(s) do you use?',
       'C/C++:What other language(s) do you use?',
       'PHP:What other language(s) do you use?',
       'C#:What other language(s) do you use?',
       'Ruby:What other language(s) do you use?',
       'Bash / Shell:What other language(s) do you use?',
       ...
       'Technical support:Which of the following best describes your job role(s)?',
       'Data analyst:Which of the following best describes your job role(s)?',
       'Business analyst:Which of the following best describes your job role(s)?',
       'Team lead:Which of the following best describes your job role(s)?',
       'Product manager:Which of the following best describes your job role(s)?',
       'CIO / CEO / CTO:Which of the following best describes your job role(s)?',
       'Systems analyst:Which of the following best describes your job role(s)?',
       'Other  Write In::Which of the following best describes your job role(s)?',
       'Could you tell us your age range?', 'What country do you live in?'],
      dtype='object', length=284)

In [8]:

raw_data.shape

(19835, 284)

In [9]:
raw_data.head()

,Unnamed: 0,Is Python the main language you use for your current projects?,None:What other language(s) do you use?,Java:What other language(s) do you use?,JavaScript:What other language(s) do you use?,C/C++:What other language(s) do you use?,PHP:What other language(s) do you use?,C#:What other language(s) do you use?,Ruby:What other language(s) do you use?,Bash / Shell:What other language(s) do you use?,...,Technical support:Which of the following best describes your job role(s)?,Data analyst:Which of the following best describes your job role(s)?,Business analyst:Which of the following best describes your job role(s)?,Team lead:Which of the following best describes your job role(s)?,Product manager:Which of the following best describes your job role(s)?,CIO / CEO / CTO:Which of the following best describes your job role(s)?,Systems analyst:Which of the following best describes your job role(s)?,Other Write In::Which of the following best describes your job role(s)?,Could you tell us your age range?,What country do you live in?
0,1,"No, I don’t use Python for my current projects",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50–59,Antigua and Barbuda
1,2,"No, I don’t use Python for my current projects",NaN,NaN,JavaScript,NaN,PHP,NaN,NaN,Bash / Shell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30–39,Italy
2,3,"No, I don’t use Python for my current projects",NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50–59,United States
3,4,"No, I don’t use Python for my current projects",NaN,Java,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30–39,United Kingdom
4,5,"No, I don’t use Python for my current projects",NaN,Java,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,United States

In [10]:
# List of all columns that were asked

for index, columns in enumerate(raw_data.columns):
    print('#{}: {}'.format(index+1,  columns))

#1: Unnamed: 0
#2: Is Python the main language you use for your current projects?
#3: None:What other language(s) do you use?
#4: Java:What other language(s) do you use?
#5: JavaScript:What other language(s) do you use?
#6: C/C++:What other language(s) do you use?
#7: PHP:What other language(s) do you use?
#8: C#:What other language(s) do you use?
#9: Ruby:What other language(s) do you use?
#10: Bash / Shell:What other language(s) do you use?
#11: Objective-C:What other language(s) do you use?
#12: Go:What other language(s) do you use?
#13: Visual Basic:What other language(s) do you use?
#14: Scala:What other language(s) do you use?
#15: SQL:What other language(s) do you use?
#16: Kotlin:What other language(s) do you use?
#17: R:What other language(s) do you use?
#18: Swift:What other language(s) do you use?
#19: Clojure:What other language(s) do you use?
#20: Perl:What other language(s) do you use?
#21: Rust:What other language(s) do you use?
#22: Groovy:What other language(s) do you use?
#23: TypeScript:What other language(s) do you use?
#24: CoffeeScript:What other language(s) do you use?
#25: HTML/CSS:What other language(s) do you use?
#26: Other - Write In::What other language(s) do you use?
#27: For what purposes do you mainly use Python?
#28: Educational purposes:What do you use Python for?
#29: Data analysis:What do you use Python for?
#30: DevOps / System administration / Writing automation scripts:What do you use Python for?
#31: Software testing / Writing automated tests:What do you use Python for?
#32: Software prototyping:What do you use Python for?
#33: Web development:What do you use Python for?
#34: Machine learning:What do you use Python for?
#35: Mobile development:What do you use Python for?
#36: Desktop development:What do you use Python for?
#37: Computer graphics:What do you use Python for?
#38: Network programming:What do you use Python for?
#39: Game development:What do you use Python for?
#40: Multimedia applications development:What do you use Python for?
#41: Embedded development:What do you use Python for?
#42: Programming of web parsers / scrapers / crawlers:What do you use Python for?
#43: Other - Write In::What do you use Python for?
#44: Educational purposes:To what extent are you involvedin the following activities?
#45: Data analysis:To what extent are you involvedin the following activities?
#46: DevOps / System administration / Writing automation scripts:To what extent are you involvedin the following activities?
#47: Software testing / Writing automated tests:To what extent are you involvedin the following activities?
#48: Software prototyping:To what extent are you involvedin the following activities?
#49: Web development:To what extent are you involvedin the following activities?
#50: Machine learning:To what extent are you involvedin the following activities?
#51: Mobile development:To what extent are you involvedin the following activities?
#52: Desktop development:To what extent are you involvedin the following activities?
#53: Computer graphics:To what extent are you involvedin the following activities?
#54: Network programming:To what extent are you involvedin the following activities?
#55: Game development:To what extent are you involvedin the following activities?
#56: Multimedia applications development:To what extent are you involvedin the following activities?
#57: Embedded development:To what extent are you involvedin the following activities?
#58: Programming of web parsers / scrapers / crawlers:To what extent are you involvedin the following activities?
#59: Other - Write In::To what extent are you involvedin the following activities?
#60: What do you use Python for the most?
#61: Do you consider yourself as a Data-Scientist?
#62: Which version of Python do you use the most?
#63: Which version of Python 2 do you use the most?
#64: Which version of Python 3 do you use the most?
#65: I dont update:What do you typically use to upgrade your Python version?
#66: Somebody else manages Python updates for me:What do you typically use to upgrade your Python version?
#67: Python.org:What do you typically use to upgrade your Python version?
#68: Build from source:What do you typically use to upgrade your Python version?
#69: Automatic upgrade via cloud provider:What do you typically use to upgrade your Python version?
#70: Enthought:What do you typically use to upgrade your Python version?
#71: Anaconda:What do you typically use to upgrade your Python version?
#72: ActivePython:What do you typically use to upgrade your Python version?
#73: Intel Distribution for Python:What do you typically use to upgrade your Python version?
#74: OS-provided Python (via apt-get, yum, homebrew, etc.):What do you typically use to upgrade your Python version?
#75: pyenv:What do you typically use to upgrade your Python version?
#76: pythonz:What do you typically use to upgrade your Python version?
#77: I use Docker containers:What do you typically use to upgrade your Python version?
#78: Other  Write In::What do you typically use to upgrade your Python version?
#79: None:Do you use any of the following tools to isolate Python environments, if any?
#80: Virtualenv / pipenv:Do you use any of the following tools to isolate Python environments, if any?
#81: Conda:Do you use any of the following tools to isolate Python environments, if any?
#82: Docker:Do you use any of the following tools to isolate Python environments, if any?
#83: Vagrant  / virtual machines:Do you use any of the following tools to isolate Python environments, if any?
#84: Other  Write In::Do you use any of the following tools to isolate Python environments, if any?
#85: None:What web frameworks / libraries do you use in addition to Python?
#86: Django:What web frameworks / libraries do you use in addition to Python?
#87: TurboGears:What web frameworks / libraries do you use in addition to Python?
#88: web2py:What web frameworks / libraries do you use in addition to Python?
#89: Bottle:What web frameworks / libraries do you use in addition to Python?
#90: CherryPy:What web frameworks / libraries do you use in addition to Python?
#91: Flask:What web frameworks / libraries do you use in addition to Python?
#92: Hug:What web frameworks / libraries do you use in addition to Python?
#93: Pyramid:What web frameworks / libraries do you use in addition to Python?
#94: Tornado:What web frameworks / libraries do you use in addition to Python?
#95: Falcon:What web frameworks / libraries do you use in addition to Python?
#96: Other  Write In::What web frameworks / libraries do you use in addition to Python?
#97: None:What data science framework(s) do you use in addition to Python?
#98: NumPy:What data science framework(s) do you use in addition to Python?
#99: SciPy:What data science framework(s) do you use in addition to Python?
#100: Pandas:What data science framework(s) do you use in addition to Python?
#101: Matplotlib:What data science framework(s) do you use in addition to Python?
#102: Seaborn:What data science framework(s) do you use in addition to Python?
#103: SciKit-Learn:What data science framework(s) do you use in addition to Python?
#104: Keras:What data science framework(s) do you use in addition to Python?
#105: TensorFlow:What data science framework(s) do you use in addition to Python?
#106: Theano:What data science framework(s) do you use in addition to Python?
#107: NLTK:What data science framework(s) do you use in addition to Python?
#108: Gensim:What data science framework(s) do you use in addition to Python?
#109: Other - Write In::What data science framework(s) do you use in addition to Python?
#110: None:Which of the following frameworks / libraries do you use in addition to Python?
#111: Requests:Which of the following frameworks / libraries do you use in addition to Python?
#112: aiohttp:Which of the following frameworks / libraries do you use in addition to Python?
#113: PyQT:Which of the following frameworks / libraries do you use in addition to Python?
#114: PyGTK:Which of the following frameworks / libraries do you use in addition to Python?
#115: wxPython:Which of the following frameworks / libraries do you use in addition to Python?
#116: Pillow:Which of the following frameworks / libraries do you use in addition to Python?
#117: Tkinter:Which of the following frameworks / libraries do you use in addition to Python?
#118: Pygame:Which of the following frameworks / libraries do you use in addition to Python?
#119: Twisted:Which of the following frameworks / libraries do you use in addition to Python?
#120: Asyncio:Which of the following frameworks / libraries do you use in addition to Python?
#121: Kivy:Which of the following frameworks / libraries do you use in addition to Python?
#122: Six:Which of the following frameworks / libraries do you use in addition to Python?
#123: Scrapy:Which of the following frameworks / libraries do you use in addition to Python?
#124: Other  Write In::Which of the following frameworks / libraries do you use in addition to Python?
#125: None:Which of the following cloud platforms do you use?
#126: Google Cloud Platform:Which of the following cloud platforms do you use?
#127: AWS:Which of the following cloud platforms do you use?
#128: Microsoft Azure:Which of the following cloud platforms do you use?
#129: Rackspace:Which of the following cloud platforms do you use?
#130: Heroku:Which of the following cloud platforms do you use?
#131: DigitalOcean:Which of the following cloud platforms do you use?
#132: Linode:Which of the following cloud platforms do you use?
#133: PythonAnywhere:Which of the following cloud platforms do you use?
#134: OpenShift:Which of the following cloud platforms do you use?
#135: OpenStack:Which of the following cloud platforms do you use?
#136: Other  Write In::Which of the following cloud platforms do you use?
#137: None of the following:How do you run code in the cloud (in the production environment)?
#138: In virtual machines:How do you run code in the cloud (in the production environment)?
#139: Within containers:How do you run code in the cloud (in the production environment)?
#140: On a Platform-as-a-Service (such as Heroku or Google App Engine):How do you run code in the cloud (in the production environment)?
#141: Serverless (such as AWS Lambda or Cloud Functions):How do you run code in the cloud (in the production environment)?
#142: Other  Write In::How do you run code in the cloud (in the production environment)?
#143: None of the following:How do you develop for the cloud?
#144: With local system interpreter:How do you develop for the cloud?
#145: Locally with virtualenv (or similar):How do you develop for the cloud?
#146: In Docker containers:How do you develop for the cloud?
#147: In virtual machines:How do you develop for the cloud?
#148: In remote development environments:How do you develop for the cloud?
#149: Directly in the production environment:How do you develop for the cloud?
#150: Other  Write In::How do you develop for the cloud?
#151: Windows:What operating system(s) are your development environment?
#152: Linux:What operating system(s) are your development environment?
#153: macOS:What operating system(s) are your development environment?
#154: BSD:What operating system(s) are your development environment?
#155: Other  Write In::What operating system(s) are your development environment?
#156: None:Which Python unit-testing framework(s) do you use, if any?
#157: pytest:Which Python unit-testing framework(s) do you use, if any?
#158: nose:Which Python unit-testing framework(s) do you use, if any?
#159: unittest:Which Python unit-testing framework(s) do you use, if any?
#160: doctest:Which Python unit-testing framework(s) do you use, if any?
#161: Tox:Which Python unit-testing framework(s) do you use, if any?
#162: Hypothesis:Which Python unit-testing framework(s) do you use, if any?
#163: mock:Which Python unit-testing framework(s) do you use, if any?
#164: Other  Write In::Which Python unit-testing framework(s) do you use, if any?
#165: None:What ORM(s) do you use together with Python, if any?
#166: Django ORM:What ORM(s) do you use together with Python, if any?
#167: SQLAlchemy:What ORM(s) do you use together with Python, if any?
#168: Peewee:What ORM(s) do you use together with Python, if any?
#169: Dejavu:What ORM(s) do you use together with Python, if any?
#170: PonyORM:What ORM(s) do you use together with Python, if any?
#171: SQLObject:What ORM(s) do you use together with Python, if any?
#172: Tortoise ORM:What ORM(s) do you use together with Python, if any?
#173: Other  Write In::What ORM(s) do you use together with Python, if any?
#174: None:Which database(s) do you regularly use, if any?
#175: DB2:Which database(s) do you regularly use, if any?
#176: MS SQL Server:Which database(s) do you regularly use, if any?
#177: MySQL:Which database(s) do you regularly use, if any?
#178: Oracle Database:Which database(s) do you regularly use, if any?
#179: PostgreSQL:Which database(s) do you regularly use, if any?
#180: SQLite:Which database(s) do you regularly use, if any?
#181: Cassandra:Which database(s) do you regularly use, if any?
#182: Couchbase:Which database(s) do you regularly use, if any?
#183: HBase:Which database(s) do you regularly use, if any?
#184: MongoDB:Which database(s) do you regularly use, if any?
#185: Neo4j:Which database(s) do you regularly use, if any?
#186: Redis:Which database(s) do you regularly use, if any?
#187: Amazon Redshift:Which database(s) do you regularly use, if any?
#188: h2:Which database(s) do you regularly use, if any?
#189: Other  Write In::Which database(s) do you regularly use, if any?
#190: None:Which of the following Big Data tool(s) do you use, if any?
#191: Apache Beam:Which of the following Big Data tool(s) do you use, if any?
#192: Apache Flink:Which of the following Big Data tool(s) do you use, if any?
#193: Apache Hadoop/MapReduce:Which of the following Big Data tool(s) do you use, if any?
#194: Apache Hive:Which of the following Big Data tool(s) do you use, if any?
#195: Apache Samza:Which of the following Big Data tool(s) do you use, if any?
#196: Apache Kafka:Which of the following Big Data tool(s) do you use, if any?
#197: Apache Spark:Which of the following Big Data tool(s) do you use, if any?
#198: Apache Tez:Which of the following Big Data tool(s) do you use, if any?
#199: Dask:Which of the following Big Data tool(s) do you use, if any?
#200: ClickHouse:Which of the following Big Data tool(s) do you use, if any?
#201: Other  Write In::Which of the following Big Data tool(s) do you use, if any?
#202: None:Which Continuous Integration (CI) system(s) do you regularly use?
#203: Jenkins / Hudson:Which Continuous Integration (CI) system(s) do you regularly use?
#204: TeamCity:Which Continuous Integration (CI) system(s) do you regularly use?
#205: Bamboo:Which Continuous Integration (CI) system(s) do you regularly use?
#206: Travis CI:Which Continuous Integration (CI) system(s) do you regularly use?
#207: CircleCI:Which Continuous Integration (CI) system(s) do you regularly use?
#208: CruiseControl:Which Continuous Integration (CI) system(s) do you regularly use?
#209: Gitlab CI:Which Continuous Integration (CI) system(s) do you regularly use?
#210: AppVeyor:Which Continuous Integration (CI) system(s) do you regularly use?
#211: Other  Write In::Which Continuous Integration (CI) system(s) do you regularly use?
#212: None:Which configuration management tools do you use, if any?
#213: Salt:Which configuration management tools do you use, if any?
#214: Puppet:Which configuration management tools do you use, if any?
#215: Chef:Which configuration management tools do you use, if any?
#216: Ansible:Which configuration management tools do you use, if any?
#217: Custom solution:Which configuration management tools do you use, if any?
#218: Other  Write In::Which configuration management tools do you use, if any?
#219: What is the main editor you use for your current Python development?
#220: None:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#221: PyCharm Professional Edition:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#222: PyCharm Community Edition:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#223: Sublime Text:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#224: Vim:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#225: Atom:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#226: VS Code:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#227: Eclipse + Pydev:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#228: Aptana:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#229: Jupyter Notebook:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#230: IntelliJ IDEA:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#231: NotePad++:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#232: IDLE:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#233: Emacs:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#234: Python Tools for Visual Studio (PTVS):What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#235: NetBeans:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#236: Spyder:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#237: Rodeo:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#238: Gedit:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#239: Ninja-IDE:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#240: Komodo Editor:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#241: Komodo IDE:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#242: Wing IDE:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#243: TextMate:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#244: None:What editors/IDEs do you usefor Python development in addition to your main ide/editor?_1
#245: Other  Write In::What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#246: Do youregularly work on multiple projects at the same time?
#247: use autocompletion  in your editor:When developing in Python, how often do you ?
#248: use a debugger:When developing in Python, how often do you ?
#249: refactor your code:When developing in Python, how often do you ?
#250: use Version Control Systems:When developing in Python, how often do you ?
#251: use code linting (programs that analyze code for potential errors):When developing in Python, how often do you ?
#252: use Python virtual environments for your projects:When developing in Python, how often do you ?
#253: use SQL databases :When developing in Python, how often do you ?
#254: use NoSQL databases:When developing in Python, how often do you ?
#255: run / debug or edit code on remote machines (remote hosts, VMs, etc.):When developing in Python, how often do you ?
#256: use a Python profiler:When developing in Python, how often do you ?
#257: write tests for your code:When developing in Python, how often do you ?
#258: use code coverage:When developing in Python, how often do you ?
#259: use optional type hinting:When developing in Python, how often do you ?

###  Characteristics of the Dataset
We see from the above checks that the:

- dataset has `19,835` rows and `284` columns
- questions asked were placed in columns
- each option in a multi-choice question is stored as a new column in the dataset
- missing values are stored as `NaN`
- once the user says they dont use python as their main language for the first question then the only relevant question for that user is the last 2 namely:

>Could you tell us your age range?

**AND**

>What country do you live in?

### Our goal

Looking at how the data is structured, I think that the best way to structure this data for analysis is to extract the answers of each question and store them in different sheets in an excel file with each sheet having the name of the excel files. 

This, I believe would make it easy to analyze and process the data. 

In summary, we have to do the following:
- each question and extract their answers
- clean data extracted and get it ready for analysis
- export cleaned data into an excel sheet whose sheet name is the question
- save the data to a file

The final output of this notebook therefore is the excel_file. Let us start by creating 2 subsets of the origin dataframe that contains:
- Answers to questions when the user uses python
- Answers to questions when the user does not use python

### Question 1

The first question is what we would use to create two observation subsets

In [117]:
# observations for python files that do not have
NOT_PYTHON_STR = 'No, I don’t use Python for my current projects'

In [118]:
# extracting the observations into two dataframes
NON_PYTHON_OBSERVATIONS_DF = raw_data[raw_data.iloc[:, 1] == NOT_PYTHON_STR]
PYTHON_OBSERVATIONS_DF = raw_data[raw_data.iloc[:, 1] != NOT_PYTHON_STR]

In [119]:
print(NON_PYTHON_OBSERVATIONS_DF.iloc[:, 1].value_counts())
NON_PYTHON_OBSERVATIONS_DF.head()

No, I don’t use Python for my current projects    1404
Name: Is Python the main language you use for your current projects?, dtype: int64

,Unnamed: 0,Is Python the main language you use for your current projects?,None:What other language(s) do you use?,Java:What other language(s) do you use?,JavaScript:What other language(s) do you use?,C/C++:What other language(s) do you use?,PHP:What other language(s) do you use?,C#:What other language(s) do you use?,Ruby:What other language(s) do you use?,Bash / Shell:What other language(s) do you use?,...,Technical support:Which of the following best describes your job role(s)?,Data analyst:Which of the following best describes your job role(s)?,Business analyst:Which of the following best describes your job role(s)?,Team lead:Which of the following best describes your job role(s)?,Product manager:Which of the following best describes your job role(s)?,CIO / CEO / CTO:Which of the following best describes your job role(s)?,Systems analyst:Which of the following best describes your job role(s)?,Other Write In::Which of the following best describes your job role(s)?,Could you tell us your age range?,What country do you live in?
0,1,"No, I don’t use Python for my current projects",None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50–59,Antigua and Barbuda
1,2,"No, I don’t use Python for my current projects",NaN,NaN,JavaScript,NaN,PHP,NaN,NaN,Bash / Shell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30–39,Italy
2,3,"No, I don’t use Python for my current projects",NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50–59,United States
3,4,"No, I don’t use Python for my current projects",NaN,Java,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30–39,United Kingdom
4,5,"No, I don’t use Python for my current projects",NaN,Java,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,United States

In [120]:
print(PYTHON_OBSERVATIONS_DF.iloc[:, 1].value_counts())
PYTHON_OBSERVATIONS_DF.head()

Yes                                         15404
No, I use Python as a secondary language     3027
Name: Is Python the main language you use for your current projects?, dtype: int64

,Unnamed: 0,Is Python the main language you use for your current projects?,None:What other language(s) do you use?,Java:What other language(s) do you use?,JavaScript:What other language(s) do you use?,C/C++:What other language(s) do you use?,PHP:What other language(s) do you use?,C#:What other language(s) do you use?,Ruby:What other language(s) do you use?,Bash / Shell:What other language(s) do you use?,...,Technical support:Which of the following best describes your job role(s)?,Data analyst:Which of the following best describes your job role(s)?,Business analyst:Which of the following best describes your job role(s)?,Team lead:Which of the following best describes your job role(s)?,Product manager:Which of the following best describes your job role(s)?,CIO / CEO / CTO:Which of the following best describes your job role(s)?,Systems analyst:Which of the following best describes your job role(s)?,Other Write In::Which of the following best describes your job role(s)?,Could you tell us your age range?,What country do you live in?
1404,1405,Yes,NaN,Java,JavaScript,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40–49,United States
1405,1406,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18–20,Nigeria
1406,1407,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21–29,United States
1407,1408,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,...,NaN,NaN,NaN,NaN,NaN,CIO / CEO / CTO,NaN,NaN,50–59,United States
1408,1409,Yes,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Team lead,NaN,NaN,NaN,NaN,40–49,United Kingdom

From the above we have successfully put all observations of python users into the `PYTHON_OBSERVATIONS_DF` constant and all non users into `NON_PYTHON_OBSERVATIONS_DF`


Now we are ready to start processing our questions

## Question 2

In this multi choice question, the users were asked:
> What other language(s) do you use?

The options of this question spans across mulitiple columns number 2 to 25.

In [133]:
question_two = PYTHON_OBSERVATIONS_DF.iloc[:, 2:26]

In [134]:
question_two

,None:What other language(s) do you use?,Java:What other language(s) do you use?,JavaScript:What other language(s) do you use?,C/C++:What other language(s) do you use?,PHP:What other language(s) do you use?,C#:What other language(s) do you use?,Ruby:What other language(s) do you use?,Bash / Shell:What other language(s) do you use?,Objective-C:What other language(s) do you use?,Go:What other language(s) do you use?,...,R:What other language(s) do you use?,Swift:What other language(s) do you use?,Clojure:What other language(s) do you use?,Perl:What other language(s) do you use?,Rust:What other language(s) do you use?,Groovy:What other language(s) do you use?,TypeScript:What other language(s) do you use?,CoffeeScript:What other language(s) do you use?,HTML/CSS:What other language(s) do you use?,Other - Write In::What other language(s) do you use?
1404,NaN,Java,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1405,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1406,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other - Write In:
1408,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Clojure,NaN,Rust,NaN,NaN,NaN,HTML/CSS,NaN
1409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1410,NaN,Java,JavaScript,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,Go,...,R,NaN,NaN,NaN,Rust,NaN,NaN,NaN,NaN,Other - Write In:
1411,NaN,Java,NaN,C/C++,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1412,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1414,NaN,NaN,JavaScript,NaN,PHP,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1415,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1417,NaN,NaN,NaN,NaN,PHP,NaN,Ruby,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1419,NaN,Java,JavaScript,NaN,PHP,C#,NaN,Bash / Shell,NaN,Go,...,NaN,NaN,NaN,NaN,Rust,NaN,TypeScript,NaN,HTML/CSS,Other - Write In:
1420,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1421,NaN,NaN,JavaScript,NaN,PHP,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1422,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CoffeeScript,HTML/CSS,Other - Write In:
1423,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,Other - Write In:
1424,NaN,NaN,NaN,NaN,NaN,C#,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1425,NaN,NaN,JavaScript,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1426,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1427,NaN,NaN,JavaScript,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1428,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
1429,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1430,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,Go,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1432,NaN,NaN,NaN,NaN,NaN,C#,NaN,Bash / Shell,NaN,NaN,...,NaN,Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other - Write In:
1433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19805,NaN,Java,JavaScript,C/C++,PHP,C#,NaN,Bash / Shell,NaN,NaN,...,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,Go,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19807,NaN,NaN,NaN,NaN,NaN,C#,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,Other - Write In:
19808,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19809,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19810,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19811,NaN,NaN,JavaScript,NaN,NaN,C#,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19812,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19813,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19814,NaN,NaN,NaN,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19815,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19816,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,Other - Write In:
19817,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,Go,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19818,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19819,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,Other - Write In:
19820,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other - Write In:
19822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19823,NaN,NaN,NaN,C/C++,NaN,C#,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other - Write In:
19824,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19825,NaN,Java,JavaScript,C/C++,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19826,NaN,NaN,JavaScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,Go,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19829,NaN,Java,NaN,C/C++,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19830,NaN,NaN,JavaScript,C/C++,NaN,C#,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN
19832,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19833,NaN,Java,NaN,C/C++,NaN,NaN,NaN,NaN,NaN,NaN,...,R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19834,NaN,NaN,JavaScript,NaN,NaN,NaN,Ruby,Bash / Shell,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS,NaN

In [123]:
melted_observations = pd.melt(question_two, var_name='option', value_name='reply')

# melted_observations = melted_observations[ melted_observations.reply.dropna()]
melted_observations  = melted_observations.dropna()

print(melted_observations.option.value_counts())
print('-----------')
print(melted_observations.reply.value_counts())

JavaScript:What other language(s) do you use?           9233
HTML/CSS:What other language(s) do you use?             8633
Bash / Shell:What other language(s) do you use?         8245
SQL:What other language(s) do you use?                  7451
C/C++:What other language(s) do you use?                5757
Java:What other language(s) do you use?                 4161
PHP:What other language(s) do you use?                  2385
C#:What other language(s) do you use?                   2077
Other - Write In::What other language(s) do you use?    1900
Go:What other language(s) do you use?                   1734
R:What other language(s) do you use?                    1589
TypeScript:What other language(s) do you use?           1385
None:What other language(s) do you use?                 1015
Ruby:What other language(s) do you use?                  800
Visual Basic:What other language(s) do you use?          757
Rust:What other language(s) do you use?                  741
Perl:What other language(s) do you use?                  545
Kotlin:What other language(s) do you use?                517
Scala:What other language(s) do you use?                 509
Swift:What other language(s) do you use?                 448
Groovy:What other language(s) do you use?                307
Objective-C:What other language(s) do you use?           254
CoffeeScript:What other language(s) do you use?          151
Clojure:What other language(s) do you use?               145
Name: option, dtype: int64
-----------
JavaScript           9233
HTML/CSS             8633
Bash / Shell         8245
SQL                  7451
C/C++                5757
Java                 4161
PHP                  2385
C#                   2077
Other - Write In:    1900
Go                   1734
R                    1589
TypeScript           1385
None                 1015
Ruby                  800
Visual Basic          757
Rust                  741
Perl                  545
Kotlin                517
Scala                 509
Swift                 448
Groovy                307
Objective-C           254
CoffeeScript          151
Clojure               145
Name: reply, dtype: int64

In [124]:
lamda_func = lambda row: 'What other language(s) do you use?'

melted_observations.option = melted_observations.apply(lamda_func,axis=1)

melted_observations.reply = melted_observations.reply.astype('category')
melted_observations.option = melted_observations.option.astype('category')
melted_observations.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60739 entries, 26 to 442332
Data columns (total 2 columns):
option    60739 non-null category
reply     60739 non-null category
dtypes: category(2)
memory usage: 594.1 KB

In [125]:
# converting the option to the question title

melted_observations.head()

                                 option reply
26   What other language(s) do you use?  None
64   What other language(s) do you use?  None
159  What other language(s) do you use?  None
206  What other language(s) do you use?  None
209  What other language(s) do you use?  None

In [126]:
sheet_ready_question_two = melted_observations.pivot(columns='option' , values='reply')

In [127]:
sheet_ready_question_two.describe()
sheet_ready_question_two.iloc[:, 0] .value_counts()

JavaScript           9233
HTML/CSS             8633
Bash / Shell         8245
SQL                  7451
C/C++                5757
Java                 4161
PHP                  2385
C#                   2077
Other - Write In:    1900
Go                   1734
R                    1589
TypeScript           1385
None                 1015
Ruby                  800
Visual Basic          757
Rust                  741
Perl                  545
Kotlin                517
Scala                 509
Swift                 448
Groovy                307
Objective-C           254
CoffeeScript          151
Clojure               145
Name: What other language(s) do you use?, dtype: int64

We have successfully prepared the question two data for analysis and stored it in the `sheet_ready_question_two` variable. Next is to process question three


Next let us process the next question 

## Question 3 

> For what purposes do you mainly use Python?

The above is single choice question with the options
- For work
- For personal education
- Both for work and personal

In [140]:
question_three = PYTHON_OBSERVATIONS_DF.iloc[:, [26]]
question_three.head()

     For what purposes do you mainly use Python?
1404                  Both for work and personal
1405                  Both for work and personal
1406                                    For work
1407                  Both for work and personal
1408                  Both for work and personal

In [144]:
question_three.iloc[:, 0].value_counts()

Both for work and personal                     10987
For personal, educational  or side projects     3852
For work                                        3592
Name: For what purposes do you mainly use Python?, dtype: int64

The data is in the exact shape and structure as we want it. Thus we can say that this data is ready to be exported to the excel sheets

In [145]:
sheet_ready_question_three = question_three

### Question 4

This is a multi-choice question that has the same structure like question one. Each option is stored as a column. We would like to do the exact same cleaning as before. 

Looking at this right now, we see that there is a need to abstract the steps of cleanning the data into functions. Thus, making it easy to re-shape similar data

What we are going to do here, is to create functions that handle the extraction of multi-choice question

In [154]:
# Let us first get the dataframe for the questions

question_four_df = PYTHON_OBSERVATIONS_DF.iloc[:, 27:43]

question_four_df.head()

,Educational purposes:What do you use Python for?,Data analysis:What do you use Python for?,DevOps / System administration / Writing automation scripts:What do you use Python for?,Software testing / Writing automated tests:What do you use Python for?,Software prototyping:What do you use Python for?,Web development:What do you use Python for?,Machine learning:What do you use Python for?,Mobile development:What do you use Python for?,Desktop development:What do you use Python for?,Computer graphics:What do you use Python for?,Network programming:What do you use Python for?,Game development:What do you use Python for?,Multimedia applications development:What do you use Python for?,Embedded development:What do you use Python for?,Programming of web parsers / scrapers / crawlers:What do you use Python for?,Other - Write In::What do you use Python for?
1404,NaN,Data analysis,DevOps / System administration / Writing autom...,Software testing / Writing automated tests,NaN,NaN,Machine learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1405,NaN,Data analysis,NaN,NaN,NaN,Web development,Machine learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1406,Educational purposes,NaN,DevOps / System administration / Writing autom...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Network programming,NaN,NaN,NaN,NaN,NaN
1407,NaN,Data analysis,DevOps / System administration / Writing autom...,Software testing / Writing automated tests,Software prototyping,Web development,NaN,NaN,Desktop development,NaN,Network programming,NaN,NaN,NaN,Programming of web parsers / scrapers / crawlers,NaN
1408,NaN,Data analysis,DevOps / System administration / Writing autom...,Software testing / Writing automated tests,NaN,Web development,Machine learning,NaN,NaN,NaN,Network programming,NaN,NaN,NaN,Programming of web parsers / scrapers / crawlers,NaN

In [313]:
def reshape_data(dataframe, question_asked, var_name='question', value_name='answer_chosen', fillna_with_str='', dropna=True ):
    melted_observations = pd.melt(dataframe, var_name=var_name, value_name=value_name)

    # melted_observations = melted_observations[ melted_observations.reply.dropna()]
    if dropna:
        melted_observations  = melted_observations.dropna()
    else:
        melted_observations  = melted_observations.fillna(fillna_with_str)

    lamda_func = lambda row: question_asked

    melted_observations[var_name] = melted_observations.apply(lamda_func,axis=1)
    
    pivoted_data = melted_observations.pivot(columns=var_name , values=value_name)
    return pivoted_data

In [314]:
sheet_ready_question_four = reshape_data(question_four_df, question_asked='What do you use Python for?')
sheet_ready_question_four.head()

question What do you use Python for?
2               Educational purposes
5               Educational purposes
6               Educational purposes
7               Educational purposes
8               Educational purposes

In [185]:
sheet_ready_question_four.iloc[:, 0].value_counts(dropna=False)

Data analysis                                                  10615
Web development                                                 9656
DevOps / System administration / Writing automation scripts     7853
Machine learning                                                7074
Programming of web parsers / scrapers / crawlers                6799
Software testing / Writing automated tests                      5859
Educational purposes                                            5108
Software prototyping                                            4955
Network programming                                             3755
Desktop development                                             3442
Computer graphics                                               1694
Embedded development                                            1482
Other - Write In:                                               1312
Game development                                                1186
Mobile development                                               836
Multimedia applications development                              639
Name: What do you use Python for?, dtype: int64

In [164]:
sheet_ready_question_four.iloc[:, 0].describe()

count             72265
unique               16
top       Data analysis
freq              10615
Name: What do you use Python for?, dtype: object

In [167]:
sheet_ready_question_four.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 72265 entries, 2 to 294882
Data columns (total 1 columns):
What do you use Python for?    72265 non-null object
dtypes: object(1)
memory usage: 1.1+ MB



#### Pipped question from question 4


The following questions(**question 5 and 6**) were piped for question 4: 

**Question 5**
> To what extent are you involved in the following activities?

The answer to this question has the following properties:
- all the option from `question 4`*(what do you use python for?)* are repeated as columns and the values are either primary activity, secondary activity or hobby
- the options the user answered from `question 4` are all contained in this question

**Question 6**
> What do you use Python for most?

This value of this question is `Nan` if the user selected only one answer from `question 4`. Thus, we can assume that the answer to this question when the value is `Nan` is the one answer the user selected

**Question 7**
> Do you consider yourself as a Data-Scientist?

This question is displayed if the user selects "Data analysis" or "Machine learning" as the answer to question_four. Thus, we can replace the `Nan` with `I do neither data science nor machine learning`

In [244]:
question_five = PYTHON_OBSERVATIONS_DF.iloc[:, 43:59]
question_five.head()

,Educational purposes:To what extent are you involvedin the following activities?,Data analysis:To what extent are you involvedin the following activities?,DevOps / System administration / Writing automation scripts:To what extent are you involvedin the following activities?,Software testing / Writing automated tests:To what extent are you involvedin the following activities?,Software prototyping:To what extent are you involvedin the following activities?,Web development:To what extent are you involvedin the following activities?,Machine learning:To what extent are you involvedin the following activities?,Mobile development:To what extent are you involvedin the following activities?,Desktop development:To what extent are you involvedin the following activities?,Computer graphics:To what extent are you involvedin the following activities?,Network programming:To what extent are you involvedin the following activities?,Game development:To what extent are you involvedin the following activities?,Multimedia applications development:To what extent are you involvedin the following activities?,Embedded development:To what extent are you involvedin the following activities?,Programming of web parsers / scrapers / crawlers:To what extent are you involvedin the following activities?,Other - Write In::To what extent are you involvedin the following activities?
1404,NaN,primary activity,secondary activity,secondary activity,NaN,NaN,hobby,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1405,NaN,primary activity,NaN,NaN,NaN,primary activity,primary activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1406,hobby,NaN,primary activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,primary activity,NaN,NaN,NaN,NaN,NaN
1407,NaN,secondary activity,primary activity,secondary activity,hobby,secondary activity,NaN,NaN,secondary activity,NaN,primary activity,NaN,NaN,NaN,secondary activity,NaN
1408,NaN,primary activity,secondary activity,secondary activity,NaN,primary activity,secondary activity,NaN,NaN,NaN,secondary activity,NaN,NaN,NaN,secondary activity,NaN

In [175]:
sheet_ready_question_five = reshape_data(question_five, question_asked='To what extent are you involvedin the following activities?')
sheet_ready_question_five.head()

question To what extent are you involvedin the following activities?
2                                                     hobby
5                                          primary activity
6                                          primary activity
7                                          primary activity
8                                        secondary activity

In [176]:
sheet_ready_question_four.shape

(72265, 1)

In [177]:
sheet_ready_question_five.shape

(72265, 1)

In [258]:
sheet_ready_question_five = pd.merge(sheet_ready_question_four, sheet_ready_question_five,left_index=True, right_index=True)

In [260]:
print(sheet_ready_question_five.shape)
sheet_ready_question_five.head()

(72265, 2)

question,What do you use Python for?,To what extent are you involvedin the following activities?
2,Educational purposes,hobby
5,Educational purposes,primary activity
6,Educational purposes,primary activity
7,Educational purposes,primary activity
8,Educational purposes,secondary activity

In [233]:
question_six = PYTHON_OBSERVATIONS_DF.iloc[:, [59]]
question_six.head()
print(question_six.shape)
question_six = pd.merge(question_four_df, question_six, left_index=True, right_index=True)

(18431, 1)

In [234]:
print(question_six.iloc[:, -1].value_counts(dropna=False))
print(question_six.shape)
question_six.iloc[:, [-1]].head()

Web development                                                4364
Data analysis                                                  2800
NaN                                                            2184
Machine learning                                               1785
DevOps / System administration / Writing automation scripts    1738
Educational purposes                                           1191
Other - Write In:                                               872
Desktop development                                             685
Software prototyping                                            630
Programming of web parsers / scrapers / crawlers                595
Software testing / Writing automated tests                      560
Network programming                                             457
Embedded development                                            198
Game development                                                158
Computer graphics                                                94
Multimedia applications development                              70
Mobile development                                               50
Name: What do you use Python for the most?, dtype: int64
(18431, 17)

                   What do you use Python for the most?
1404                                      Data analysis
1405                                    Web development
1406  DevOps / System administration / Writing autom...
1407                               Software prototyping
1408                                    Web development

In [241]:
def change_all_nans_to_main_use(row):
    """Replaces the nan values
    
    Replaces the nan values in the column 'What do you use Python for the most?'
    with the answer to the question 'What do you use Python for?'
    
    """
    users_most_python_use_case = row[-1]
    if isinstance(users_most_python_use_case, float) and  math.isnan(users_most_python_use_case) :

        primary_use_case = next(item for item in row.values if isinstance(item, str))
        row[-1]= primary_use_case
        
    return row

question_six_with_no_nans  = question_six.apply(change_all_nans_to_main_use,axis=1)
question_six_with_no_nans.iloc[:, -1].value_counts(dropna=False)

question_six_with_no_nans = question_six_with_no_nans.iloc[:,[ -1]]
question_six_with_no_nans.head()

                   What do you use Python for the most?
1404                                      Data analysis
1405                                    Web development
1406  DevOps / System administration / Writing autom...
1407                               Software prototyping
1408                                    Web development

In [242]:

question_six_with_no_nans.iloc[:,0].value_counts(dropna=False)

Web development                                                5072
Data analysis                                                  3136
DevOps / System administration / Writing automation scripts    1950
Machine learning                                               1923
Educational purposes                                           1496
Other - Write In:                                               876
Desktop development                                             780
Software prototyping                                            650
Software testing / Writing automated tests                      650
Programming of web parsers / scrapers / crawlers                637
Network programming                                             501
Embedded development                                            233
Game development                                                211
Computer graphics                                               169
Multimedia applications development                              81
Mobile development                                               66
Name: What do you use Python for the most?, dtype: int64

In [ ]:
sheet_ready_question_six = question_six_with_no_nans

In [254]:
question_seven = PYTHON_OBSERVATIONS_DF.iloc[:, [60]]
question_seven.head()

     Do you consider yourself as a Data-Scientist?
1404                                            No
1405                                            No
1406                                           NaN
1407                                            No
1408                                            No

In [255]:
question_seven.iloc[:, 0].value_counts(dropna=False)

No                   7509
NaN                  6582
Yes                  3606
Other – Write In:     734
Name: Do you consider yourself as a Data-Scientist?, dtype: int64

In [257]:
sheet_ready_question_seven = \
    question_seven.fillna('I do neither data science nor machine learning')
sheet_ready_question_seven.iloc[:, 0].value_counts(dropna=False)

No                                                7509
I do neither data science nor machine learning    6582
Yes                                               3606
Other – Write In:                                  734
Name: Do you consider yourself as a Data-Scientist?, dtype: int64

#### Question 8

> Which version of Python do you use the most?*

There are only two possible answers to this question namely:
- Python 2
- Python 3

In [262]:
# Extracting the answers to question 8 and storing it in the variable question_eight
question_eight = PYTHON_OBSERVATIONS_DF.iloc[:, [61]]
print(question_eight.iloc[:, 0].value_counts(dropna=False))
question_eight.head()

Python 3    15446
Python 2     2985
Name: Which version of Python do you use the most?, dtype: int64

     Which version of Python do you use the most?
1404                                     Python 3
1405                                     Python 3
1406                                     Python 3
1407                                     Python 3
1408                                     Python 3

The data above is as clean as can be as there are no Nan values

In [264]:
# Since the data is sheet ready we store it in sheet_ready_question_eight variable
sheet_ready_question_eight = question_eight
sheet_ready_question_eight.shape

(18431, 1)

#### Pipped question from question 8

The next two questions are dependent on the answer of question 8

**Quesiton 9**
>Which version of Python 2 do you use the most?*

The above question is displayed when the user selects `python 2` in  question 8

**Quesiton 10**
>Which version of Python 3 do you use the most?*

The above question is displayed when the user selects `python 3` in  question 8


Nan logic
---
 
When the question is not displayed to the user,  then `Nan` is put as the value. I think we can just dropna for both questions

In [265]:
# Extracting the answers to question 9 and storing it in the variable question_nine
question_nine = PYTHON_OBSERVATIONS_DF.iloc[:, [62]]
print(question_nine.iloc[:, 0].value_counts(dropna=False))
question_nine.head()

NaN           15605
Python 2.7     2630
Python 2.6       65
Python 2.0       46
Python 2.4       20
Python 2.1       18
Python 2.5       17
Python 2.3       16
Python 2.2       14
Name: Which version of Python 2 do you use the most?, dtype: int64

     Which version of Python 2 do you use the most?
1404                                            NaN
1405                                            NaN
1406                                            NaN
1407                                            NaN
1408                                            NaN

In [267]:
# Extracting the answers to question 10 and storing it in the variable question_ten
question_ten = PYTHON_OBSERVATIONS_DF.iloc[:, [63]]
print(question_ten.iloc[:, 0].value_counts(dropna=False))
question_ten.head()

Python 3.6    7812
Python 3.7    4277
NaN           4089
Python 3.5    1550
Python 3.4     394
Python 3.0      94
Python 3.2      75
Python 3.1      72
Python 3.3      68
Name: Which version of Python 3 do you use the most?, dtype: int64

     Which version of Python 3 do you use the most?
1404                                     Python 3.6
1405                                     Python 3.7
1406                                     Python 3.6
1407                                     Python 3.6
1408                                     Python 3.5

In [271]:
sheet_ready_question_nine = question_nine.dropna()
sheet_ready_question_ten = question_ten.dropna()

print(sheet_ready_question_nine.iloc[:, 0].value_counts())
print('-----')
print(sheet_ready_question_ten.iloc[:, 0].value_counts())

Python 2.7    2630
Python 2.6      65
Python 2.0      46
Python 2.4      20
Python 2.1      18
Python 2.5      17
Python 2.3      16
Python 2.2      14
Name: Which version of Python 2 do you use the most?, dtype: int64
-----
Python 3.6    7812
Python 3.7    4277
Python 3.5    1550
Python 3.4     394
Python 3.0      94
Python 3.2      75
Python 3.1      72
Python 3.3      68
Name: Which version of Python 3 do you use the most?, dtype: int64

#### Question 11

> What do you typically use to upgrade your Python version?

The above is a multi-choice question whose options are stored in column index 64 to 77. We would process this using the `reshape_data` function that reshapes multi-choice questions

In [277]:
question_eleven = PYTHON_OBSERVATIONS_DF.iloc[:, 64:78]
print(question_eleven.shape)
question_eleven.head()

(18431, 14)

,I dont update:What do you typically use to upgrade your Python version?,Somebody else manages Python updates for me:What do you typically use to upgrade your Python version?,Python.org:What do you typically use to upgrade your Python version?,Build from source:What do you typically use to upgrade your Python version?,Automatic upgrade via cloud provider:What do you typically use to upgrade your Python version?,Enthought:What do you typically use to upgrade your Python version?,Anaconda:What do you typically use to upgrade your Python version?,ActivePython:What do you typically use to upgrade your Python version?,Intel Distribution for Python:What do you typically use to upgrade your Python version?,"OS-provided Python (via apt-get, yum, homebrew, etc.):What do you typically use to upgrade your Python version?",pyenv:What do you typically use to upgrade your Python version?,pythonz:What do you typically use to upgrade your Python version?,I use Docker containers:What do you typically use to upgrade your Python version?,Other Write In::What do you typically use to upgrade your Python version?
1404,NaN,NaN,NaN,NaN,NaN,NaN,Anaconda,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1405,NaN,NaN,NaN,NaN,NaN,NaN,Anaconda,NaN,Intel Distribution for Python,NaN,NaN,NaN,NaN,NaN
1406,NaN,NaN,Python.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1407,NaN,NaN,Python.org,NaN,NaN,NaN,NaN,NaN,NaN,"OS-provided Python (via apt-get, yum, homebrew...",NaN,NaN,NaN,NaN
1408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"OS-provided Python (via apt-get, yum, homebrew...",NaN,NaN,I use Docker containers,NaN

In [280]:

sheet_ready_question_eleven = \
reshape_data(question_eleven, question_asked='What do you typically use to upgrade your Python version?')

print(sheet_ready_question_eleven.shape)
sheet_ready_question_eleven.iloc[:, 0].value_counts()

(27697, 1)

OS-provided Python (via apt-get, yum, homebrew, etc.)    6912
Python.org                                               6128
Anaconda                                                 4054
I use Docker containers                                  2788
pyenv                                                    2728
I don’t update                                           1539
Build from source                                        1297
Somebody else manages Python updates for me               854
Other – Write In:                                         606
Automatic upgrade via cloud provider                      348
Intel Distribution for Python                             171
ActivePython                                              151
pythonz                                                    69
Enthought                                                  52
Name: What do you typically use to upgrade your Python version?, dtype: int64

#### Question 12

> Do you use any of the following tools to isolate Python environments, if any?

The above is a multi-choice question whose options are stored in column index 78 to 83. We do exactly what we did for question 11

In [367]:
question_twelve = PYTHON_OBSERVATIONS_DF.iloc[:, 78:84]
print(question_twelve.shape)
question_twelve.head()

(18431, 6)

,"None:Do you use any of the following tools to isolate Python environments, if any?","Virtualenv / pipenv:Do you use any of the following tools to isolate Python environments, if any?","Conda:Do you use any of the following tools to isolate Python environments, if any?","Docker:Do you use any of the following tools to isolate Python environments, if any?","Vagrant / virtual machines:Do you use any of the following tools to isolate Python environments, if any?","Other Write In::Do you use any of the following tools to isolate Python environments, if any?"
1404,None,NaN,NaN,NaN,NaN,NaN
1405,NaN,NaN,Conda,NaN,NaN,NaN
1406,None,NaN,NaN,NaN,NaN,NaN
1407,NaN,Virtualenv / pipenv,NaN,NaN,NaN,NaN
1408,NaN,Virtualenv / pipenv,NaN,Docker,NaN,NaN

In [368]:
question_12_str = 'Do you use any of the following tools to isolate Python environments, if any?'
sheet_ready_question_twelve = \
reshape_data(question_twelve, question_asked=question_12_str)

print(sheet_ready_question_twelve.shape)
sheet_ready_question_twelve.iloc[:, 0].value_counts()

(27636, 1)

Virtualenv / pipenv            11729
Docker                          5787
Conda                           4084
None                            3800
Vagrant  / virtual machines     1676
Other – Write In:                560
Name: Do you use any of the following tools to isolate Python environments, if any?, dtype: int64

#### Question 13

> What web frameworks / libraries do you use in addition to Python?

Multi question with columns spanning index 83 to 95. Similar processing

In [369]:
# Extracting the data
question_13_str = 'What web frameworks / libraries do you use in addition to Python?'

question_thirteen = PYTHON_OBSERVATIONS_DF.iloc[:, 84:96]
print(question_thirteen.shape)
question_thirteen.head()

(18431, 12)

,None:What web frameworks / libraries do you use in addition to Python?,Django:What web frameworks / libraries do you use in addition to Python?,TurboGears:What web frameworks / libraries do you use in addition to Python?,web2py:What web frameworks / libraries do you use in addition to Python?,Bottle:What web frameworks / libraries do you use in addition to Python?,CherryPy:What web frameworks / libraries do you use in addition to Python?,Flask:What web frameworks / libraries do you use in addition to Python?,Hug:What web frameworks / libraries do you use in addition to Python?,Pyramid:What web frameworks / libraries do you use in addition to Python?,Tornado:What web frameworks / libraries do you use in addition to Python?,Falcon:What web frameworks / libraries do you use in addition to Python?,Other Write In::What web frameworks / libraries do you use in addition to Python?
1404,NaN,NaN,NaN,NaN,NaN,NaN,Flask,NaN,NaN,NaN,NaN,NaN
1405,NaN,Django,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1406,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1407,NaN,Django,NaN,NaN,NaN,NaN,Flask,NaN,NaN,NaN,NaN,NaN
1408,NaN,Django,NaN,NaN,NaN,NaN,Flask,NaN,NaN,Tornado,NaN,NaN

In [296]:
sheet_ready_question_thirteen = \
reshape_data(question_thirteen, question_asked=question_13_str)

print(sheet_ready_question_thirteen.shape)
sheet_ready_question_thirteen.iloc[:, 0].value_counts(dropna=False)

(54890, 1)

Virtualenv / pipenv            11729
Flask                           8615
None                            8473
Django                          8354
Docker                          5787
Conda                           4084
Other – Write In:               1732
Vagrant  / virtual machines     1676
Tornado                         1080
Pyramid                          720
web2py                           693
Bottle                           684
CherryPy                         543
Falcon                           456
Hug                              159
TurboGears                       105
Name: What web frameworks / libraries do you use in addition to Python?, dtype: int64

#### Question 14

> What data science framework(s) do you use in addition to Python?

Multi question with columns spanning index 96 to 108. Similar processing

In [299]:
question_14_str = 'What data science framework(s) do you use in addition to Python?'
question_fourteen = PYTHON_OBSERVATIONS_DF.iloc[:, 96:109]
print(question_fourteen.shape)
question_fourteen.head()

(18431, 13)

,None:What data science framework(s) do you use in addition to Python?,NumPy:What data science framework(s) do you use in addition to Python?,SciPy:What data science framework(s) do you use in addition to Python?,Pandas:What data science framework(s) do you use in addition to Python?,Matplotlib:What data science framework(s) do you use in addition to Python?,Seaborn:What data science framework(s) do you use in addition to Python?,SciKit-Learn:What data science framework(s) do you use in addition to Python?,Keras:What data science framework(s) do you use in addition to Python?,TensorFlow:What data science framework(s) do you use in addition to Python?,Theano:What data science framework(s) do you use in addition to Python?,NLTK:What data science framework(s) do you use in addition to Python?,Gensim:What data science framework(s) do you use in addition to Python?,Other - Write In::What data science framework(s) do you use in addition to Python?
1404,NaN,NumPy,NaN,Pandas,Matplotlib,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1405,NaN,NaN,NaN,Pandas,Matplotlib,NaN,NaN,Keras,TensorFlow,NaN,NaN,NaN,NaN
1406,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1407,NaN,NumPy,SciPy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1408,NaN,NumPy,NaN,Pandas,NaN,NaN,SciKit-Learn,NaN,NaN,NaN,NaN,NaN,NaN

In [302]:
sheet_ready_question_fourteen = \
reshape_data(question_fourteen, question_asked=question_14_str)

print(sheet_ready_question_fourteen.shape)
sheet_ready_question_fourteen.iloc[:, 0].value_counts(dropna=False)

(61707, 1)

NumPy                11384
Pandas                9314
Matplotlib            8434
SciPy                 6989
SciKit-Learn          5787
None                  5018
TensorFlow            4653
Keras                 2776
Seaborn               2713
NLTK                  2413
Other - Write In:      909
Gensim                 760
Theano                 557
Name: What data science framework(s) do you use in addition to Python?, dtype: int64

The last few processing seemed similar. Although most of the work was done in the function `reshape_data`, it turns out that there are some repetitions.

I would like to spend some time creating functions that automate these repetitions

In [307]:

def reshape_and_show_info(question_asked, start_index, end_index):
    untidy_question_df = PYTHON_OBSERVATIONS_DF.iloc[:, start_index:end_index]
    print('---Initial Shape---')
    print(question_fourteen.shape)
    reshaped_df = \
    reshape_data(untidy_question_df, question_asked=question_asked)
    
    print('---Shape after reshaping---')
    print(reshaped_df.shape)
    print(reshaped_df.iloc[:, 0].value_counts(dropna=False))
    return reshaped_df

Subsequently, I would simply cann the function `reshape_and_show_info` for multi-choice questions

#### Question 15

> Which of the following frameworks / libraries do you use in addition to Python?

Multi question with columns spanning index 109 to 123. Would be processed using the `reshape_and_show_info `

In [310]:
question_15_str = 'Which of the following frameworks / libraries do you use in addition to Python?'

sheet_ready_question_fifteen = reshape_and_show_info( question_15_str, 109, 124)
sheet_ready_question_fifteen

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(43581, 1)
Requests             9834
Pillow               5430
Scrapy               3462
Asyncio              3311
Tkinter              3303
None                 3285
PyQT                 2985
Six                  2620
aiohttp              1948
Pygame               1943
Other – Write In:    1364
wxPython             1131
Twisted              1125
Kivy                 1043
PyGTK                 797
Name: Which of the following frameworks / libraries do you use in addition to Python?, dtype: int64

question Which of the following frameworks / libraries do you use in addition to Python?
0                                                      None
12                                                     None
20                                                     None
25                                                     None
29                                                     None
44                                                     None
45                                                     None
50                                                     None
67                                                     None
93                                                     None
102                                                    None
104                                                    None
107                                                    None
117                                                    None
126                                                    None
133                                                    None
137                                                    None
141                                                    None
154                                                    None
166                                                    None
169                                                    None
171                                                    None
183                                                    None
187                                                    None
199                                                    None
224                                                    None
225                                                    None
230                                                    None
234                                                    None
236                                                    None
...                                                     ...
276029                                    Other – Write In:
276030                                    Other – Write In:
276032                                    Other – Write In:
276034                                    Other – Write In:
276044                                    Other – Write In:
276078                                    Other – Write In:
276093                                    Other – Write In:
276111                                    Other – Write In:
276113                                    Other – Write In:
276122                                    Other – Write In:
276126                                    Other – Write In:
276146                                    Other – Write In:
276163                                    Other – Write In:
276172                                    Other – Write In:
276198                                    Other – Write In:
276201                                    Other – Write In:
276232                                    Other – Write In:
276240                                    Other – Write In:
276243                                    Other – Write In:
276248                                    Other – Write In:
276253                                    Other – Write In:
276265                                    Other – Write In:
276278                                    Other – Write In:
276289                                    Other – Write In:
276303                                    Other – Write In:
276332                                    Other – Write In:
276346                                    Other – Write In:
276347                                    Other – Write In:
276356                                    Other – Write In:
276383                                    Other – Write In:

[43581 rows x 1 columns]

#### Question 16

> Which of the following cloud platforms do you use?

Multi question with columns spanning index 124 to 135. Similar processing

In [330]:
question_str ='Which of the following cloud platforms do you use?'
sheet_ready_question_sixteen = reshape_and_show_info( question_str, 124, 136)
sheet_ready_question_sixteen

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(28938, 1)
AWS                      6679
None                     6354
Google Cloud Platform    3623
DigitalOcean             3133
Heroku                   2603
Microsoft Azure          1845
PythonAnywhere           1561
Other – Write In:        1008
OpenStack                 812
Linode                    723
OpenShift                 396
Rackspace                 201
Name: Which of the following cloud platforms do you use?, dtype: int64

question Which of the following cloud platforms do you use?
2                                                      None
4                                                      None
7                                                      None
8                                                      None
12                                                     None
15                                                     None
23                                                     None
25                                                     None
26                                                     None
27                                                     None
28                                                     None
29                                                     None
31                                                     None
37                                                     None
49                                                     None
51                                                     None
53                                                     None
54                                                     None
55                                                     None
58                                                     None
62                                                     None
67                                                     None
68                                                     None
80                                                     None
83                                                     None
87                                                     None
94                                                     None
102                                                    None
104                                                    None
105                                                    None
...                                                     ...
220292                                    Other – Write In:
220293                                    Other – Write In:
220299                                    Other – Write In:
220306                                    Other – Write In:
220326                                    Other – Write In:
220347                                    Other – Write In:
220373                                    Other – Write In:
220378                                    Other – Write In:
220412                                    Other – Write In:
220425                                    Other – Write In:
220470                                    Other – Write In:
220498                                    Other – Write In:
220503                                    Other – Write In:
220508                                    Other – Write In:
220561                                    Other – Write In:
220563                                    Other – Write In:
220613                                    Other – Write In:
220645                                    Other – Write In:
220734                                    Other – Write In:
220742                                    Other – Write In:
220789                                    Other – Write In:
220820                                    Other – Write In:
220828                                    Other – Write In:
220870                                    Other – Write In:
220931                                    Other – Write In:
221011                                    Other – Write In:
221034                                    Other – Write In:
221087                                    Other – Write In:
221109                                    Other – Write In:
221168                                    Other – Write In:

[28938 rows x 1 columns]

#### Dependent questions

The next two questions are dependent on the answer of question 16

**Quesiton 17**
>How do you run code in the cloud (in the production environment)?

Spans colums 137 to 142

**Quesiton 18**
>How do you develop for the cloud?

Spans colums 143 to 151

They are shown only when the user did not choose `None` in question 16. Thus, Nan indicates that:
- the user does not use any cloud platform



Nan logic
---
 
When the question is not displayed to the user,  then `Nan` is put as the value, we replace it with `I dont use cloud computing`


Let us spend some time automating the processing for both questions in a function

In [336]:
def reshape_by_replacing_na_and_show_info(question_asked, start_index, end_index, na_str, ):
    untidy_question_df = PYTHON_OBSERVATIONS_DF.iloc[:, start_index:end_index]
    print('---Initial Shape---')
    print(untidy_question_df.shape)

    reshaped_df = \
        reshape_data(untidy_question_df, question_asked=question_asked,fillna_with_str=na_str,dropna=False)
    
    print('---Shape after reshaping---')
    print(reshaped_df.shape)
    print(reshaped_df.iloc[:, 0].value_counts(dropna=False))
    return reshaped_df

In [342]:
# processing question 17
question_str = 'How do you run code in the cloud (in the production environment)?'
na_str= 'I dont use cloud computing'
sheet_ready_question_seventeen =  \
reshape_by_replacing_na_and_show_info(question_str, 136, 142, na_str)
sheet_ready_question_seventeen.head(10)

---Initial Shape---
(18431, 6)
---Shape after reshaping---
(110586, 1)
I dont use cloud computing                                          93649
In virtual machines                                                  5308
Within containers                                                    4461
On a Platform-as-a-Service (such as Heroku or Google App Engine)     3084
Serverless (such as AWS Lambda or Cloud Functions)                   2353
None of the following                                                1451
Other – Write In:                                                     280
Name: How do you run code in the cloud (in the production environment)?, dtype: int64

question How do you run code in the cloud (in the production environment)?
0                                I dont use cloud computing
1                                I dont use cloud computing
2                                I dont use cloud computing
3                                I dont use cloud computing
4                                I dont use cloud computing
5                                I dont use cloud computing
6                                I dont use cloud computing
7                                I dont use cloud computing
8                                I dont use cloud computing
9                                I dont use cloud computing

In [340]:
# processing question 18
question_str = 'How do you develop for the cloud?'
na_str= 'I dont use cloud computing'
sheet_ready_question_eighteen =  \
reshape_by_replacing_na_and_show_info(question_str, 142, 150, na_str)
sheet_ready_question_eighteen.head(10)

---Initial Shape---
(18431, 8)
---Shape after reshaping---
(147448, 1)
I dont use cloud computing                128525
Locally with virtualenv (or similar)        6317
In Docker containers                        3940
In virtual machines                         2728
With local system interpreter               1959
In remote development environments          1855
None of the following                       1042
Directly in the production environment       968
Other – Write In:                            114
Name: How do you develop for the cloud?, dtype: int64

question How do you develop for the cloud?
0               I dont use cloud computing
1               I dont use cloud computing
2               I dont use cloud computing
3               I dont use cloud computing
4               I dont use cloud computing
5               I dont use cloud computing
6               I dont use cloud computing
7               I dont use cloud computing
8               I dont use cloud computing
9               I dont use cloud computing

#### Question 19

> What operating system(s) are your development environment?

Multi question with columns spanning index 151 to 155. Similar processing

In [343]:
question_nineteen = 'What operating system(s) are your development environment?'

sheet_ready_question_nineteen = reshape_and_show_info( question_15_str, 150, 155)
sheet_ready_question_nineteen.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(27753, 1)
Linux                12780
Windows               8703
macOS                 5806
BSD                    264
Other – Write In:      200
Name: Which of the following frameworks / libraries do you use in addition to Python?, dtype: int64

question Which of the following frameworks / libraries do you use in addition to Python?
3                                                   Windows
5                                                   Windows
11                                                  Windows
14                                                  Windows
19                                                  Windows
23                                                  Windows
26                                                  Windows
28                                                  Windows
32                                                  Windows
36                                                  Windows

#### Question 20

> Which Python unit-testing framework(s) do you use, if any?

The patterns are now looking the same. From now onwards I would just stop putting the questions in markdowns an would just go straight to extracting the questions

In [345]:
# Processing Question 20
question_str ='Which Python unit-testing framework(s) do you use, if any?'

sheet_ready_question_twenty = reshape_and_show_info( question_15_str, 155, 164)
sheet_ready_question_twenty.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(28787, 1)
pytest               8448
None                 6526
unittest             5873
mock                 2848
Tox                  1590
nose                 1576
doctest               992
Hypothesis            659
Other – Write In:     275
Name: Which of the following frameworks / libraries do you use in addition to Python?, dtype: int64

question Which of the following frameworks / libraries do you use in addition to Python?
7                                                      None
20                                                     None
21                                                     None
24                                                     None
28                                                     None
29                                                     None
38                                                     None
40                                                     None
44                                                     None
48                                                     None

In [346]:
# Processing muti-chioce Question 21
question_str ='What ORM(s) do you use together with Python, if any?'

sheet_ready_question_twenty_one = reshape_and_show_info( question_15_str,  164, 173)
sheet_ready_question_twenty_one.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(22526, 1)
None                 7941
SQLAlchemy           6268
Django ORM           6010
SQLObject             771
Peewee                663
Other – Write In:     391
PonyORM               212
Tortoise ORM          148
Dejavu                122
Name: Which of the following frameworks / libraries do you use in addition to Python?, dtype: int64

question Which of the following frameworks / libraries do you use in addition to Python?
0                                                      None
2                                                      None
7                                                      None
8                                                      None
12                                                     None
13                                                     None
19                                                     None
25                                                     None
26                                                     None
27                                                     None

In [347]:
# Processing muti-chioce Question 22
question_str ='Which database(s) do you regularly use, if any?'

sheet_ready_question_twenty_two = reshape_and_show_info( question_15_str,  173, 189)
sheet_ready_question_twenty_two.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(39970, 1)
PostgreSQL           8133
MySQL                7562
SQLite               7530
MongoDB              3774
Redis                3488
None                 2779
MS SQL Server        1992
Oracle Database      1396
Other – Write In:    1144
Amazon Redshift       555
Cassandra             480
Neo4j                 388
DB2                   249
HBase                 216
Couchbase             183
h2                    101
Name: Which of the following frameworks / libraries do you use in addition to Python?, dtype: int64

question Which of the following frameworks / libraries do you use in addition to Python?
7                                                      None
8                                                      None
25                                                     None
26                                                     None
27                                                     None
48                                                     None
49                                                     None
54                                                     None
55                                                     None
67                                                     None

In [348]:
# Processing muti-chioce Question 23
question_str ='Which of the following Big Data tool(s) do you use, if any?'

sheet_ready_question_twenty_three = reshape_and_show_info( question_15_str,  189, 201)
sheet_ready_question_twenty_three.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(21722, 1)
None                       13954
Apache Spark                2263
Apache Hadoop/MapReduce     1452
Apache Kafka                1391
Apache Hive                  827
Dask                         760
Other – Write In:            262
Apache Beam                  198
ClickHouse                   195
Apache Flink                 160
Apache Tez                   158
Apache Samza                 102
Name: Which of the following frameworks / libraries do you use in addition to Python?, dtype: int64

question Which of the following frameworks / libraries do you use in addition to Python?
1                                                      None
2                                                      None
3                                                      None
7                                                      None
8                                                      None
10                                                     None
11                                                     None
12                                                     None
13                                                     None
14                                                     None

In [357]:
# Processing muti-chioce Question 24
question_str = 'Which Continuous Integration (CI) system(s) do you regularly use?'


sheet_ready_question_twenty_four = reshape_and_show_info( question_str, 201, 211)
sheet_ready_question_twenty_four.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(23617, 1)
None                 8415
Jenkins / Hudson     4644
Gitlab CI            3407
Travis CI            3325
CircleCI             1319
Other – Write In:     868
AppVeyor              591
TeamCity              479
Bamboo                468
CruiseControl         101
Name: Which Continuous Integration (CI) system(s) do you regularly use?, dtype: int64

question Which Continuous Integration (CI) system(s) do you regularly use?
1                                                      None
7                                                      None
8                                                      None
11                                                     None
17                                                     None
20                                                     None
21                                                     None
24                                                     None
28                                                     None
29                                                     None

In [358]:
# Processing muti-chioce Question 25
question_str = 'Which configuration management tools do you use, if any?'


sheet_ready_question_twenty_five = reshape_and_show_info( question_str, 211, 218)
sheet_ready_question_twenty_five.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(20217, 1)
None                 11921
Ansible               3621
Custom solution       1627
Puppet                1033
Salt                   825
Chef                   669
Other – Write In:      521
Name: Which configuration management tools do you use, if any?, dtype: int64

question Which configuration management tools do you use, if any?
1                                                      None
2                                                      None
5                                                      None
7                                                      None
8                                                      None
9                                                      None
12                                                     None
14                                                     None
16                                                     None
18                                                     None

In [359]:
# Processing muti-chioce Question 26
question_str = 'What is the main editor you use for your current Python development?'
# 

sheet_ready_question_twenty_six = reshape_and_show_info( question_str, 218, 219)
sheet_ready_question_twenty_six.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(18431, 1)
PyCharm Professional Edition             3581
VS Code                                  2952
PyCharm Community Edition                2641
Vim                                      1831
Sublime Text                             1545
Jupyter Notebook                          976
Atom                                      974
IDLE                                      664
Emacs                                     564
Spyder                                    463
Other – Write In:                         450
IntelliJ IDEA                             373
NotePad++                                 343
Eclipse + Pydev                           312
None                                      309
Python Tools for Visual Studio (PTVS)     128
Wing IDE                                   82
Gedit                                      80
NetBeans                                   45
Komodo Editor                              28
TextMate                                   23
Komodo IDE                                 23
Aptana                                     20
Ninja-IDE                                  17
Rodeo                                       7
Name: What is the main editor you use for your current Python development?, dtype: int64

question What is the main editor you use for your current Python development?
0                                                 NotePad++
1                                                   VS Code
2                                 PyCharm Community Edition
3                                                     Emacs
4                                                  Wing IDE
5                                                      Atom
6                              PyCharm Professional Edition
7                              PyCharm Professional Edition
8                                         Other – Write In:
9                              PyCharm Professional Edition

In [360]:
# Processing muti-chioce Question 27
question_str = \
'What editors/IDEs do you use for Python development in addition to your main ide/editor?'


sheet_ready_question_twenty_seven = reshape_and_show_info( question_str, 219, 245)
sheet_ready_question_twenty_seven.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(34821, 1)
Vim                                      4581
Jupyter Notebook                         3881
Sublime Text                             3460
VS Code                                  3341
PyCharm Community Edition                2864
None                                     2784
NotePad++                                2745
Atom                                     2188
IDLE                                     1676
PyCharm Professional Edition             1345
Spyder                                   1044
Other – Write In:                         876
Gedit                                     789
IntelliJ IDEA                             680
Python Tools for Visual Studio (PTVS)     643
Emacs                                     564
Eclipse + Pydev                           536
NetBeans                                  262
TextMate                                  148
Wing IDE                                   91
Ninja-IDE                                  88
Komodo Editor                              78
Komodo IDE                                 72
Aptana                                     51
Rodeo                                      34
Name: What editors/IDEs do you use for Python development in addition to your main ide/editor?, dtype: int64

question What editors/IDEs do you use for Python development in addition to your main ide/editor?
18471                          PyCharm Professional Edition
18474                          PyCharm Professional Edition
18518                          PyCharm Professional Edition
18550                          PyCharm Professional Edition
18554                          PyCharm Professional Edition
18574                          PyCharm Professional Edition
18588                          PyCharm Professional Edition
18599                          PyCharm Professional Edition
18611                          PyCharm Professional Edition
18616                          PyCharm Professional Edition

In [361]:
# Processing muti-chioce Question 28
question_str = \
'Do you regularly work on multiple projects at the same time?'


sheet_ready_question_twenty_eight = reshape_and_show_info( question_str, 245, 246)
sheet_ready_question_twenty_eight.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(18431, 1)
Yes, I work on many different projects               7756
Yes, I work on one main and several side projects    7611
No,  I only work on one project                      3064
Name: Do you regularly work on multiple projects at the same time?, dtype: int64

question Do you regularly work on multiple projects at the same time?
0         Yes, I work on one main and several side projects
1                    Yes, I work on many different projects
2         Yes, I work on one main and several side projects
3                    Yes, I work on many different projects
4                    Yes, I work on many different projects
5                    Yes, I work on many different projects
6                    Yes, I work on many different projects
7                    Yes, I work on many different projects
8                           No,  I only work on one project
9         Yes, I work on one main and several side projects

In [362]:
# Processing muti-chioce Question 29

question_str = 'When developing in Python, how often do'


sheet_ready_question_twenty_nine = reshape_and_show_info( question_str,246, 261)
sheet_ready_question_twenty_nine.head(10)

---Initial Shape---
(18431, 13)
---Shape after reshaping---
(206902, 1)
Often                         83423
Never or<br />Almost never    63155
From time<br />to time        60324
Name: When developing in Python, how often do, dtype: int64

question When developing in Python, how often do
0                                          Often
3                     Never or<br />Almost never
4                                          Often
8                                          Often
10                                         Often
12                    Never or<br />Almost never
13                        From time<br />to time
15                                         Often
16                                         Often
17                                         Often

In [372]:
PYTHON_OBSERVATIONS_DF.iloc[:, 261].value_counts(dropna=False)

Friend / Colleague                 4828
Search engines                     2708
School / University                2575
I don't remember                   2467
Technical review / Forum / Blog    2273
Social network                     1259
Other – Write In:                  1134
Conference / User Group             525
NaN                                 353
Advertising                         309
Name: How did you first learn aboutyour main ide/editor?, dtype: int64

In [376]:
PYTHON_OBSERVATIONS_DF.iloc[:, 218].value_counts(dropna=False)

PyCharm Professional Edition             3581
VS Code                                  2952
PyCharm Community Edition                2641
Vim                                      1831
Sublime Text                             1545
Jupyter Notebook                          976
Atom                                      974
IDLE                                      664
Emacs                                     564
Spyder                                    463
Other – Write In:                         450
IntelliJ IDEA                             373
NotePad++                                 343
Eclipse + Pydev                           312
None                                      309
Python Tools for Visual Studio (PTVS)     128
Wing IDE                                   82
Gedit                                      80
NetBeans                                   45
Komodo Editor                              28
TextMate                                   23
Komodo IDE                                 23
Aptana                                     20
Ninja-IDE                                  17
Rodeo                                       7
Name: What is the main editor you use for your current Python development?, dtype: int64

In [398]:
obs = PYTHON_OBSERVATIONS_DF.iloc[:, [218,261]]
obs[ obs.iloc[:, 0] == 'None' ]

,What is the main editor you use for your current Python development?,How did you first learn aboutyour main ide/editor?
2468,None,NaN
2656,None,NaN
3201,None,NaN
3302,None,NaN
3466,None,NaN
3794,None,NaN
3835,None,NaN
3920,None,NaN
3938,None,NaN
4011,None,NaN
4107,None,NaN
4108,None,NaN
4158,None,NaN
4177,None,NaN
4183,None,NaN
4231,None,NaN
4283,None,NaN
4290,None,NaN
4298,None,NaN
4367,None,NaN
4386,None,NaN
4401,None,NaN
4573,None,NaN
4640,None,NaN
4666,None,NaN
4720,None,NaN
4738,None,NaN
4757,None,NaN
4775,None,NaN
4814,None,NaN
...,...,...
18238,None,NaN
18266,None,NaN
18371,None,NaN
18396,None,NaN
18422,None,NaN
18425,None,NaN
18491,None,NaN
18552,None,NaN
18616,None,NaN
18779,None,NaN
18920,None,NaN
18933,None,NaN
18994,None,NaN
19028,None,NaN
19047,None,NaN
19055,None,NaN
19076,None,NaN
19190,None,NaN
19285,None,NaN
19291,None,NaN
19401,None,NaN
19440,None,NaN
19458,None,NaN
19481,None,NaN
19485,None,NaN
19497,None,NaN
19609,None,NaN
19638,None,NaN
19655,None,NaN
19681,None,NaN

In [411]:
obs[pd.isna( obs.iloc[:, -1] )].iloc[:, 0].value_counts(dropna=False)
# obs[ isinstance(obs.iloc[:, -1], float)].iloc[:, -1].value_counts(dropna=False)

None                                     308
PyCharm Community Edition                  7
PyCharm Professional Edition               7
IDLE                                       5
Sublime Text                               4
Atom                                       4
VS Code                                    4
Eclipse + Pydev                            3
Vim                                        3
NotePad++                                  3
Spyder                                     2
Python Tools for Visual Studio (PTVS)      1
Komodo Editor                              1
IntelliJ IDEA                              1
Name: What is the main editor you use for your current Python development?, dtype: int64

In [414]:
PYTHON_OBSERVATIONS_DF.iloc[:, 264].value_counts(dropna=False)

NaN                    10312
2-7 people              6036
8-12 people             1370
13-20 people             429
21-40 people             158
More than 40 people      126
Name: How many people are in your project team?, dtype: int64

In [415]:


PYTHON_OBSERVATIONS_DF.iloc[:, 263].value_counts(dropna=False)

Work in a team                               8879
Work on your own project(s) independently    8846
Work as an external consultant or trainer     706
Name: Most of the time, do you ...?, dtype: int64

In [420]:
# 263
obsve_32 = PYTHON_OBSERVATIONS_DF.iloc[:, 263:265]
obsve_32[obsve_32.iloc[:, 0] == 'Work in a team'].iloc[:,-1].value_counts(dropna=False)

2-7 people             6036
8-12 people            1370
NaN                     760
13-20 people            429
21-40 people            158
More than 40 people     126
Name: How many people are in your project team?, dtype: int64

In [422]:
obsve_32[pd.isna(obsve_32.iloc[:, -1])].iloc[:,0].value_counts(dropna=False)

Work on your own project(s) independently    8846
Work in a team                                760
Work as an external consultant or trainer     706
Name: Most of the time, do you ...?, dtype: int64

In [425]:
# 266
PYTHON_OBSERVATIONS_DF.iloc[:, 265].value_counts(dropna=False)

Fully employed by a company / organization                                                                 11353
Student                                                                                                     3535
Freelancer <em>(a person pursuing a profession without a long-term commitment to any one employer)</em>     1136
Self-employed <em>(a person earning income directly from one's own business, trade, or profession)</em>     1072
Partially employed by a company / organization                                                               795
Other – Write In:                                                                                            390
Retired                                                                                                      150
Name: What is your employment status?, dtype: int64

In [426]:
PYTHON_OBSERVATIONS_DF.iloc[:, 266].value_counts(dropna=False)

NaN                6302
51–500             3030
11–50              2338
More than 5,000    2330
2–10               1484
1,001–5,000        1255
501–1,000           806
Just me             609
Not sure            277
Name: How many people work for your company / organization?, dtype: int64

In [433]:
obser = PYTHON_OBSERVATIONS_DF.iloc[:, [266]]
obser

      How many people work for your company / organization?
1404                                     More than 5,000
1405                                             Just me
1406                                              51–500
1407                                              51–500
1408                                               11–50
1409                                                 NaN
1410                                                 NaN
1411                                                 NaN
1412                                                 NaN
1413                                     More than 5,000
1414                                              51–500
1415                                     More than 5,000
1416                                               11–50
1417                                         1,001–5,000
1418                                                2–10
1419                                               11–50
1420                                              51–500
1421                                              51–500
1422                                                 NaN
1423                                                 NaN
1424                                                 NaN
1425                                              51–500
1426                                                2–10
1427                                     More than 5,000
1428                                         1,001–5,000
1429                                         1,001–5,000
1430                                                 NaN
1431                                         1,001–5,000
1432                                               11–50
1433                                                 NaN
...                                                  ...
19805                                               2–10
19806                                             51–500
19807                                              11–50
19808                                        1,001–5,000
19809                                           Not sure
19810                                               2–10
19811                                            Just me
19812                                        1,001–5,000
19813                                             51–500
19814                                             51–500
19815                                             51–500
19816                                               2–10
19817                                                NaN
19818                                        1,001–5,000
19819                                               2–10
19820                                    More than 5,000
19821                                    More than 5,000
19822                                                NaN
19823                                        1,001–5,000
19824                                              11–50
19825                                            Just me
19826                                                NaN
19827                                                NaN
19828                                        1,001–5,000
19829                                                NaN
19830                                              11–50
19831                                             51–500
19832                                             51–500
19833                                                NaN
19834                                             51–500

[18431 rows x 1 columns]

In [434]:

for index, columns in enumerate(raw_data.columns):
    print('#{}: {}'.format(index+1,  columns))

#1: Unnamed: 0
#2: Is Python the main language you use for your current projects?
#3: None:What other language(s) do you use?
#4: Java:What other language(s) do you use?
#5: JavaScript:What other language(s) do you use?
#6: C/C++:What other language(s) do you use?
#7: PHP:What other language(s) do you use?
#8: C#:What other language(s) do you use?
#9: Ruby:What other language(s) do you use?
#10: Bash / Shell:What other language(s) do you use?
#11: Objective-C:What other language(s) do you use?
#12: Go:What other language(s) do you use?
#13: Visual Basic:What other language(s) do you use?
#14: Scala:What other language(s) do you use?
#15: SQL:What other language(s) do you use?
#16: Kotlin:What other language(s) do you use?
#17: R:What other language(s) do you use?
#18: Swift:What other language(s) do you use?
#19: Clojure:What other language(s) do you use?
#20: Perl:What other language(s) do you use?
#21: Rust:What other language(s) do you use?
#22: Groovy:What other language(s) do you use?
#23: TypeScript:What other language(s) do you use?
#24: CoffeeScript:What other language(s) do you use?
#25: HTML/CSS:What other language(s) do you use?
#26: Other - Write In::What other language(s) do you use?
#27: For what purposes do you mainly use Python?
#28: Educational purposes:What do you use Python for?
#29: Data analysis:What do you use Python for?
#30: DevOps / System administration / Writing automation scripts:What do you use Python for?
#31: Software testing / Writing automated tests:What do you use Python for?
#32: Software prototyping:What do you use Python for?
#33: Web development:What do you use Python for?
#34: Machine learning:What do you use Python for?
#35: Mobile development:What do you use Python for?
#36: Desktop development:What do you use Python for?
#37: Computer graphics:What do you use Python for?
#38: Network programming:What do you use Python for?
#39: Game development:What do you use Python for?
#40: Multimedia applications development:What do you use Python for?
#41: Embedded development:What do you use Python for?
#42: Programming of web parsers / scrapers / crawlers:What do you use Python for?
#43: Other - Write In::What do you use Python for?
#44: Educational purposes:To what extent are you involvedin the following activities?
#45: Data analysis:To what extent are you involvedin the following activities?
#46: DevOps / System administration / Writing automation scripts:To what extent are you involvedin the following activities?
#47: Software testing / Writing automated tests:To what extent are you involvedin the following activities?
#48: Software prototyping:To what extent are you involvedin the following activities?
#49: Web development:To what extent are you involvedin the following activities?
#50: Machine learning:To what extent are you involvedin the following activities?
#51: Mobile development:To what extent are you involvedin the following activities?
#52: Desktop development:To what extent are you involvedin the following activities?
#53: Computer graphics:To what extent are you involvedin the following activities?
#54: Network programming:To what extent are you involvedin the following activities?
#55: Game development:To what extent are you involvedin the following activities?
#56: Multimedia applications development:To what extent are you involvedin the following activities?
#57: Embedded development:To what extent are you involvedin the following activities?
#58: Programming of web parsers / scrapers / crawlers:To what extent are you involvedin the following activities?
#59: Other - Write In::To what extent are you involvedin the following activities?
#60: What do you use Python for the most?
#61: Do you consider yourself as a Data-Scientist?
#62: Which version of Python do you use the most?
#63: Which version of Python 2 do you use the most?
#64: Which version of Python 3 do you use the most?
#65: I dont update:What do you typically use to upgrade your Python version?
#66: Somebody else manages Python updates for me:What do you typically use to upgrade your Python version?
#67: Python.org:What do you typically use to upgrade your Python version?
#68: Build from source:What do you typically use to upgrade your Python version?
#69: Automatic upgrade via cloud provider:What do you typically use to upgrade your Python version?
#70: Enthought:What do you typically use to upgrade your Python version?
#71: Anaconda:What do you typically use to upgrade your Python version?
#72: ActivePython:What do you typically use to upgrade your Python version?
#73: Intel Distribution for Python:What do you typically use to upgrade your Python version?
#74: OS-provided Python (via apt-get, yum, homebrew, etc.):What do you typically use to upgrade your Python version?
#75: pyenv:What do you typically use to upgrade your Python version?
#76: pythonz:What do you typically use to upgrade your Python version?
#77: I use Docker containers:What do you typically use to upgrade your Python version?
#78: Other  Write In::What do you typically use to upgrade your Python version?
#79: None:Do you use any of the following tools to isolate Python environments, if any?
#80: Virtualenv / pipenv:Do you use any of the following tools to isolate Python environments, if any?
#81: Conda:Do you use any of the following tools to isolate Python environments, if any?
#82: Docker:Do you use any of the following tools to isolate Python environments, if any?
#83: Vagrant  / virtual machines:Do you use any of the following tools to isolate Python environments, if any?
#84: Other  Write In::Do you use any of the following tools to isolate Python environments, if any?
#85: None:What web frameworks / libraries do you use in addition to Python?
#86: Django:What web frameworks / libraries do you use in addition to Python?
#87: TurboGears:What web frameworks / libraries do you use in addition to Python?
#88: web2py:What web frameworks / libraries do you use in addition to Python?
#89: Bottle:What web frameworks / libraries do you use in addition to Python?
#90: CherryPy:What web frameworks / libraries do you use in addition to Python?
#91: Flask:What web frameworks / libraries do you use in addition to Python?
#92: Hug:What web frameworks / libraries do you use in addition to Python?
#93: Pyramid:What web frameworks / libraries do you use in addition to Python?
#94: Tornado:What web frameworks / libraries do you use in addition to Python?
#95: Falcon:What web frameworks / libraries do you use in addition to Python?
#96: Other  Write In::What web frameworks / libraries do you use in addition to Python?
#97: None:What data science framework(s) do you use in addition to Python?
#98: NumPy:What data science framework(s) do you use in addition to Python?
#99: SciPy:What data science framework(s) do you use in addition to Python?
#100: Pandas:What data science framework(s) do you use in addition to Python?
#101: Matplotlib:What data science framework(s) do you use in addition to Python?
#102: Seaborn:What data science framework(s) do you use in addition to Python?
#103: SciKit-Learn:What data science framework(s) do you use in addition to Python?
#104: Keras:What data science framework(s) do you use in addition to Python?
#105: TensorFlow:What data science framework(s) do you use in addition to Python?
#106: Theano:What data science framework(s) do you use in addition to Python?
#107: NLTK:What data science framework(s) do you use in addition to Python?
#108: Gensim:What data science framework(s) do you use in addition to Python?
#109: Other - Write In::What data science framework(s) do you use in addition to Python?
#110: None:Which of the following frameworks / libraries do you use in addition to Python?
#111: Requests:Which of the following frameworks / libraries do you use in addition to Python?
#112: aiohttp:Which of the following frameworks / libraries do you use in addition to Python?
#113: PyQT:Which of the following frameworks / libraries do you use in addition to Python?
#114: PyGTK:Which of the following frameworks / libraries do you use in addition to Python?
#115: wxPython:Which of the following frameworks / libraries do you use in addition to Python?
#116: Pillow:Which of the following frameworks / libraries do you use in addition to Python?
#117: Tkinter:Which of the following frameworks / libraries do you use in addition to Python?
#118: Pygame:Which of the following frameworks / libraries do you use in addition to Python?
#119: Twisted:Which of the following frameworks / libraries do you use in addition to Python?
#120: Asyncio:Which of the following frameworks / libraries do you use in addition to Python?
#121: Kivy:Which of the following frameworks / libraries do you use in addition to Python?
#122: Six:Which of the following frameworks / libraries do you use in addition to Python?
#123: Scrapy:Which of the following frameworks / libraries do you use in addition to Python?
#124: Other  Write In::Which of the following frameworks / libraries do you use in addition to Python?
#125: None:Which of the following cloud platforms do you use?
#126: Google Cloud Platform:Which of the following cloud platforms do you use?
#127: AWS:Which of the following cloud platforms do you use?
#128: Microsoft Azure:Which of the following cloud platforms do you use?
#129: Rackspace:Which of the following cloud platforms do you use?
#130: Heroku:Which of the following cloud platforms do you use?
#131: DigitalOcean:Which of the following cloud platforms do you use?
#132: Linode:Which of the following cloud platforms do you use?
#133: PythonAnywhere:Which of the following cloud platforms do you use?
#134: OpenShift:Which of the following cloud platforms do you use?
#135: OpenStack:Which of the following cloud platforms do you use?
#136: Other  Write In::Which of the following cloud platforms do you use?
#137: None of the following:How do you run code in the cloud (in the production environment)?
#138: In virtual machines:How do you run code in the cloud (in the production environment)?
#139: Within containers:How do you run code in the cloud (in the production environment)?
#140: On a Platform-as-a-Service (such as Heroku or Google App Engine):How do you run code in the cloud (in the production environment)?
#141: Serverless (such as AWS Lambda or Cloud Functions):How do you run code in the cloud (in the production environment)?
#142: Other  Write In::How do you run code in the cloud (in the production environment)?
#143: None of the following:How do you develop for the cloud?
#144: With local system interpreter:How do you develop for the cloud?
#145: Locally with virtualenv (or similar):How do you develop for the cloud?
#146: In Docker containers:How do you develop for the cloud?
#147: In virtual machines:How do you develop for the cloud?
#148: In remote development environments:How do you develop for the cloud?
#149: Directly in the production environment:How do you develop for the cloud?
#150: Other  Write In::How do you develop for the cloud?
#151: Windows:What operating system(s) are your development environment?
#152: Linux:What operating system(s) are your development environment?
#153: macOS:What operating system(s) are your development environment?
#154: BSD:What operating system(s) are your development environment?
#155: Other  Write In::What operating system(s) are your development environment?
#156: None:Which Python unit-testing framework(s) do you use, if any?
#157: pytest:Which Python unit-testing framework(s) do you use, if any?
#158: nose:Which Python unit-testing framework(s) do you use, if any?
#159: unittest:Which Python unit-testing framework(s) do you use, if any?
#160: doctest:Which Python unit-testing framework(s) do you use, if any?
#161: Tox:Which Python unit-testing framework(s) do you use, if any?
#162: Hypothesis:Which Python unit-testing framework(s) do you use, if any?
#163: mock:Which Python unit-testing framework(s) do you use, if any?
#164: Other  Write In::Which Python unit-testing framework(s) do you use, if any?
#165: None:What ORM(s) do you use together with Python, if any?
#166: Django ORM:What ORM(s) do you use together with Python, if any?
#167: SQLAlchemy:What ORM(s) do you use together with Python, if any?
#168: Peewee:What ORM(s) do you use together with Python, if any?
#169: Dejavu:What ORM(s) do you use together with Python, if any?
#170: PonyORM:What ORM(s) do you use together with Python, if any?
#171: SQLObject:What ORM(s) do you use together with Python, if any?
#172: Tortoise ORM:What ORM(s) do you use together with Python, if any?
#173: Other  Write In::What ORM(s) do you use together with Python, if any?
#174: None:Which database(s) do you regularly use, if any?
#175: DB2:Which database(s) do you regularly use, if any?
#176: MS SQL Server:Which database(s) do you regularly use, if any?
#177: MySQL:Which database(s) do you regularly use, if any?
#178: Oracle Database:Which database(s) do you regularly use, if any?
#179: PostgreSQL:Which database(s) do you regularly use, if any?
#180: SQLite:Which database(s) do you regularly use, if any?
#181: Cassandra:Which database(s) do you regularly use, if any?
#182: Couchbase:Which database(s) do you regularly use, if any?
#183: HBase:Which database(s) do you regularly use, if any?
#184: MongoDB:Which database(s) do you regularly use, if any?
#185: Neo4j:Which database(s) do you regularly use, if any?
#186: Redis:Which database(s) do you regularly use, if any?
#187: Amazon Redshift:Which database(s) do you regularly use, if any?
#188: h2:Which database(s) do you regularly use, if any?
#189: Other  Write In::Which database(s) do you regularly use, if any?
#190: None:Which of the following Big Data tool(s) do you use, if any?
#191: Apache Beam:Which of the following Big Data tool(s) do you use, if any?
#192: Apache Flink:Which of the following Big Data tool(s) do you use, if any?
#193: Apache Hadoop/MapReduce:Which of the following Big Data tool(s) do you use, if any?
#194: Apache Hive:Which of the following Big Data tool(s) do you use, if any?
#195: Apache Samza:Which of the following Big Data tool(s) do you use, if any?
#196: Apache Kafka:Which of the following Big Data tool(s) do you use, if any?
#197: Apache Spark:Which of the following Big Data tool(s) do you use, if any?
#198: Apache Tez:Which of the following Big Data tool(s) do you use, if any?
#199: Dask:Which of the following Big Data tool(s) do you use, if any?
#200: ClickHouse:Which of the following Big Data tool(s) do you use, if any?
#201: Other  Write In::Which of the following Big Data tool(s) do you use, if any?
#202: None:Which Continuous Integration (CI) system(s) do you regularly use?
#203: Jenkins / Hudson:Which Continuous Integration (CI) system(s) do you regularly use?
#204: TeamCity:Which Continuous Integration (CI) system(s) do you regularly use?
#205: Bamboo:Which Continuous Integration (CI) system(s) do you regularly use?
#206: Travis CI:Which Continuous Integration (CI) system(s) do you regularly use?
#207: CircleCI:Which Continuous Integration (CI) system(s) do you regularly use?
#208: CruiseControl:Which Continuous Integration (CI) system(s) do you regularly use?
#209: Gitlab CI:Which Continuous Integration (CI) system(s) do you regularly use?
#210: AppVeyor:Which Continuous Integration (CI) system(s) do you regularly use?
#211: Other  Write In::Which Continuous Integration (CI) system(s) do you regularly use?
#212: None:Which configuration management tools do you use, if any?
#213: Salt:Which configuration management tools do you use, if any?
#214: Puppet:Which configuration management tools do you use, if any?
#215: Chef:Which configuration management tools do you use, if any?
#216: Ansible:Which configuration management tools do you use, if any?
#217: Custom solution:Which configuration management tools do you use, if any?
#218: Other  Write In::Which configuration management tools do you use, if any?
#219: What is the main editor you use for your current Python development?
#220: None:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#221: PyCharm Professional Edition:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#222: PyCharm Community Edition:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#223: Sublime Text:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#224: Vim:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#225: Atom:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#226: VS Code:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#227: Eclipse + Pydev:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#228: Aptana:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#229: Jupyter Notebook:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#230: IntelliJ IDEA:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#231: NotePad++:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#232: IDLE:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#233: Emacs:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#234: Python Tools for Visual Studio (PTVS):What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#235: NetBeans:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#236: Spyder:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#237: Rodeo:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#238: Gedit:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#239: Ninja-IDE:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#240: Komodo Editor:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#241: Komodo IDE:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#242: Wing IDE:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#243: TextMate:What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#244: None:What editors/IDEs do you usefor Python development in addition to your main ide/editor?_1
#245: Other  Write In::What editors/IDEs do you usefor Python development in addition to your main ide/editor?
#246: Do youregularly work on multiple projects at the same time?
#247: use autocompletion  in your editor:When developing in Python, how often do you ?
#248: use a debugger:When developing in Python, how often do you ?
#249: refactor your code:When developing in Python, how often do you ?
#250: use Version Control Systems:When developing in Python, how often do you ?
#251: use code linting (programs that analyze code for potential errors):When developing in Python, how often do you ?
#252: use Python virtual environments for your projects:When developing in Python, how often do you ?
#253: use SQL databases :When developing in Python, how often do you ?
#254: use NoSQL databases:When developing in Python, how often do you ?
#255: run / debug or edit code on remote machines (remote hosts, VMs, etc.):When developing in Python, how often do you ?
#256: use a Python profiler:When developing in Python, how often do you ?
#257: write tests for your code:When developing in Python, how often do you ?
#258: use code coverage:When developing in Python, how often do you ?
#259: use optional type hinting:When developing in Python, how often do you ?

In [437]:
PYTHON_OBSERVATIONS_DF.iloc[:, [268]]

      Choose one from the list::Which of the following industries do you develop for?
1404                                                 NaN
1405                                                 NaN
1406                                               Other
1407                                                 NaN
1408                                                 NaN
1409                                                 NaN
1410                                                 NaN
1411                                                 NaN
1412                                                 NaN
1413                                                 NaN
1414                                                 NaN
1415                                                 NaN
1416                                                 NaN
1417                                               Other
1418                                                 NaN
1419                                           Marketing
1420                                                 NaN
1421                                                 NaN
1422                                                 NaN
1423                                                 NaN
1424                                                 NaN
1425                                                 NaN
1426                                                 NaN
1427                                                 NaN
1428                                                 NaN
1429                                                 NaN
1430                                                 NaN
1431       Information Technology / Software Development
1432                                                 NaN
1433                                                 NaN
...                                                  ...
19805                                                NaN
19806      Information Technology / Software Development
19807                                                NaN
19808                                                NaN
19809                                                NaN
19810      Information Technology / Software Development
19811                                                NaN
19812                                                NaN
19813      Information Technology / Software Development
19814                                                NaN
19815      Information Technology / Software Development
19816                                                NaN
19817                                                NaN
19818                                                NaN
19819                               Service/ Maintenance
19820                                                NaN
19821                                                NaN
19822                                                NaN
19823      Information Technology / Software Development
19824                                                NaN
19825                                                NaN
19826                                                NaN
19827                                                NaN
19828                                                NaN
19829                                                NaN
19830                                              Other
19831      Information Technology / Software Development
19832                                                NaN
19833                                                NaN
19834      Information Technology / Software Development

[18431 rows x 1 columns]

In [438]:
!pwd

/Users/ogbuejioforchidiebere/Documents/Programming/Python/Practice/Data Science/JBeansData